/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import {
  Contract,
  ContractFactory,
  ContractTransactionResponse,
  Interface,
} from "ethers";
import type { Signer, ContractDeployTransaction, ContractRunner } from "ethers";
import type { NonPayableOverrides } from "../../common";
import type {
  ClaimHelper,
  ClaimHelperInterface,
} from "../../contracts/ClaimHelper";

const _abi = [
  {
    inputs: [
      {
        internalType: "address",
        name: "claimHelperAddr",
        type: "address",
      },
      {
        internalType: "address",
        name: "originalSingleton",
        type: "address",
      },
      {
        internalType: "address",
        name: "governor",
        type: "address",
      },
      {
        internalType: "uint256",
        name: "proposalId",
        type: "uint256",
      },
    ],
    name: "claimAndRestore",
    outputs: [],
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    stateMutability: "payable",
    type: "receive",
  },
] as const;

const _bytecode =
  "0x608060405234801561001057600080fd5b50610231806100206000396000f3fe6080604052600436106100225760003560e01c8063318c75871461002e57600080fd5b3661002957005b600080fd5b34801561003a57600080fd5b5061004e610049366004610181565b610050565b005b600080546001600160a01b038681166001600160a01b031990921691909117825560408051602480820186905282518083039091018152604490910182526020810180516001600160e01b031663fe0d94c160e01b1790529051918516916100b891906101cc565b6000604051808303816000865af19150503d80600081146100f5576040519150601f19603f3d011682016040523d82523d6000602084013e6100fa565b606091505b505090508061013e5760405162461bcd60e51b815260206004820152600c60248201526b10db185a5b4819985a5b195960a21b604482015260640160405180910390fd5b5050600080546001600160a01b0319166001600160a01b0393909316929092179091555050565b80356001600160a01b038116811461017c57600080fd5b919050565b6000806000806080858703121561019757600080fd5b6101a085610165565b93506101ae60208601610165565b92506101bc60408601610165565b9396929550929360600135925050565b6000825160005b818110156101ed57602081860181015185830152016101d3565b50600092019182525091905056fea264697066735822122057c9c2f9ff4253074e796a0c174ce9d209c2412008182435a28c80d152c9326764736f6c63430008140033";

type ClaimHelperConstructorParams =
  | [signer?: Signer]
  | ConstructorParameters<typeof ContractFactory>;

const isSuperArgs = (
  xs: ClaimHelperConstructorParams
): xs is ConstructorParameters<typeof ContractFactory> => xs.length > 1;

export class ClaimHelper__factory extends ContractFactory {
  constructor(...args: ClaimHelperConstructorParams) {
    if (isSuperArgs(args)) {
      super(...args);
    } else {
      super(_abi, _bytecode, args[0]);
    }
  }

  override getDeployTransaction(
    overrides?: NonPayableOverrides & { from?: string }
  ): Promise<ContractDeployTransaction> {
    return super.getDeployTransaction(overrides || {});
  }
  override deploy(overrides?: NonPayableOverrides & { from?: string }) {
    return super.deploy(overrides || {}) as Promise<
      ClaimHelper & {
        deploymentTransaction(): ContractTransactionResponse;
      }
    >;
  }
  override connect(runner: ContractRunner | null): ClaimHelper__factory {
    return super.connect(runner) as ClaimHelper__factory;
  }

  static readonly bytecode = _bytecode;
  static readonly abi = _abi;
  static createInterface(): ClaimHelperInterface {
    return new Interface(_abi) as ClaimHelperInterface;
  }
  static connect(address: string, runner?: ContractRunner | null): ClaimHelper {
    return new Contract(address, _abi, runner) as unknown as ClaimHelper;
  }
}
