// SPDX-License-Identifier: MIT
pragma solidity ^0.8.20;

import "forge-std/Test.sol";
import "../../contracts/DidManifestRegistry.sol";

/**
 * @title DidManifestRegistryFuzzTest
 * @dev Fuzz tests for DidManifestRegistry. Each test receives random inputs
 *      generated by the Foundry fuzzer (1000 runs by default) and asserts
 *      that a property holds for all of them.
 */
contract DidManifestRegistryFuzzTest is Test {
    DidManifestRegistry public registry;
    address public owner;
    address public nonOwner;

    function setUp() public {
        owner = address(this);
        nonOwner = makeAddr("nonOwner");
        registry = new DidManifestRegistry();
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 1: set then get returns the same CID for any non-empty CID
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_setAndGet(bytes32 didKey, string calldata manifestCid) public {
        vm.assume(bytes(manifestCid).length > 0);

        registry.setManifestCid(didKey, manifestCid);

        assertEq(registry.getManifestCid(didKey), manifestCid);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 2: empty string always reverts with InvalidCid, for any key
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_emptyStringAlwaysReverts(bytes32 didKey) public {
        vm.expectRevert(DidManifestRegistry.InvalidCid.selector);
        registry.setManifestCid(didKey, "");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 3: any address that is not the owner is always rejected
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_nonOwnerCannotSet(
        address caller,
        bytes32 didKey,
        string calldata manifestCid
    ) public {
        vm.assume(caller != owner);
        vm.assume(caller != address(0));
        vm.assume(bytes(manifestCid).length > 0);

        vm.prank(caller);
        vm.expectRevert(
            abi.encodeWithSelector(
                bytes4(keccak256("OwnableUnauthorizedAccount(address)")),
                caller
            )
        );
        registry.setManifestCid(didKey, manifestCid);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 4: a second set on the same key always overwrites the value
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_setOverwritesValue(
        bytes32 didKey,
        string calldata firstCid,
        string calldata secondCid
    ) public {
        vm.assume(bytes(firstCid).length > 0);
        vm.assume(bytes(secondCid).length > 0);
        // Ensure they are actually different to make the assertion meaningful
        vm.assume(keccak256(bytes(firstCid)) != keccak256(bytes(secondCid)));

        registry.setManifestCid(didKey, firstCid);
        registry.setManifestCid(didKey, secondCid);

        assertEq(registry.getManifestCid(didKey), secondCid);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 5: after delete, get always returns empty string
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_deleteAfterSet(bytes32 didKey, string calldata manifestCid) public {
        vm.assume(bytes(manifestCid).length > 0);

        registry.setManifestCid(didKey, manifestCid);
        registry.deleteManifestCid(didKey);

        assertEq(registry.getManifestCid(didKey), "");
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 6: batch with mismatched array lengths always reverts ArrayMismatch
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_batchArrayMismatch(
        bytes32[] calldata didKeys,
        string[] calldata manifestCids
    ) public {
        vm.assume(didKeys.length != manifestCids.length);

        vm.expectRevert(DidManifestRegistry.ArrayMismatch.selector);
        registry.setManifestCidsBatch(didKeys, manifestCids);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 7: all keys in a valid batch are correctly retrievable
    // This test uses a bounded input to stay within gas limits.
    // When duplicate keys appear in the batch, the last write wins — so we
    // build a "last seen" mapping and only assert against that final value.
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_batchSetAndGet(bytes32[4] calldata keys, string[4] calldata cids) public {
        // Build dynamic arrays and ensure all CIDs are non-empty
        bytes32[] memory didKeys = new bytes32[](4);
        string[] memory manifestCids = new string[](4);
        for (uint256 i = 0; i < 4; i++) {
            vm.assume(bytes(cids[i]).length > 0);
            didKeys[i] = keys[i];
            manifestCids[i] = cids[i];
        }

        registry.setManifestCidsBatch(didKeys, manifestCids);

        // For each key, find the LAST occurrence in the batch (last-write wins)
        // and assert the on-chain value matches that CID.
        for (uint256 i = 0; i < 4; i++) {
            // Find last index where this key appears
            uint256 lastIdx = i;
            for (uint256 j = i + 1; j < 4; j++) {
                if (didKeys[j] == didKeys[i]) {
                    lastIdx = j;
                }
            }
            // Only assert from the perspective of the entry that "won"
            if (lastIdx == i) {
                assertEq(registry.getManifestCid(didKeys[i]), manifestCids[i]);
            }
        }
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 8: bytes32(0) is a legal key — no special casing in the contract
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_bytes32ZeroKeyIsValid(string calldata manifestCid) public {
        vm.assume(bytes(manifestCid).length > 0);

        bytes32 zeroKey = bytes32(0);
        registry.setManifestCid(zeroKey, manifestCid);

        assertEq(registry.getManifestCid(zeroKey), manifestCid);
    }

    // ─────────────────────────────────────────────────────────────────────────
    // Property 9: get on any key never previously written returns empty string
    // ─────────────────────────────────────────────────────────────────────────
    function testFuzz_nonExistentKeyReturnsEmpty(bytes32 didKey) public view {
        // Fresh contract — nothing has been written, all keys should return ""
        assertEq(registry.getManifestCid(didKey), "");
    }
}
