/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "../common";

export interface DidManifestRegistryInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "acceptOwnership"
      | "deleteManifestCid"
      | "deleteManifestCidsBatch"
      | "getManifestCid"
      | "owner"
      | "pendingOwner"
      | "renounceOwnership"
      | "setManifestCid"
      | "setManifestCidsBatch"
      | "transferOwnership"
  ): FunctionFragment;

  getEvent(
    nameOrSignatureOrTopic:
      | "ManifestCidDeleted"
      | "ManifestCidSet"
      | "ManifestCidsBatchDeleted"
      | "ManifestCidsBatchSet"
      | "OwnershipTransferStarted"
      | "OwnershipTransferred"
  ): EventFragment;

  encodeFunctionData(
    functionFragment: "acceptOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "deleteManifestCid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(
    functionFragment: "deleteManifestCidsBatch",
    values: [BytesLike[]]
  ): string;
  encodeFunctionData(
    functionFragment: "getManifestCid",
    values: [BytesLike]
  ): string;
  encodeFunctionData(functionFragment: "owner", values?: undefined): string;
  encodeFunctionData(
    functionFragment: "pendingOwner",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "renounceOwnership",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "setManifestCid",
    values: [BytesLike, string]
  ): string;
  encodeFunctionData(
    functionFragment: "setManifestCidsBatch",
    values: [BytesLike[], string[]]
  ): string;
  encodeFunctionData(
    functionFragment: "transferOwnership",
    values: [AddressLike]
  ): string;

  decodeFunctionResult(
    functionFragment: "acceptOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteManifestCid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "deleteManifestCidsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getManifestCid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(functionFragment: "owner", data: BytesLike): Result;
  decodeFunctionResult(
    functionFragment: "pendingOwner",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "renounceOwnership",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManifestCid",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "setManifestCidsBatch",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "transferOwnership",
    data: BytesLike
  ): Result;
}

export namespace ManifestCidDeletedEvent {
  export type InputTuple = [didKey: BytesLike, writer: AddressLike];
  export type OutputTuple = [didKey: string, writer: string];
  export interface OutputObject {
    didKey: string;
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManifestCidSetEvent {
  export type InputTuple = [
    didKey: BytesLike,
    manifestCid: string,
    writer: AddressLike
  ];
  export type OutputTuple = [
    didKey: string,
    manifestCid: string,
    writer: string
  ];
  export interface OutputObject {
    didKey: string;
    manifestCid: string;
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManifestCidsBatchDeletedEvent {
  export type InputTuple = [didKeys: BytesLike[], writer: AddressLike];
  export type OutputTuple = [didKeys: string[], writer: string];
  export interface OutputObject {
    didKeys: string[];
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace ManifestCidsBatchSetEvent {
  export type InputTuple = [
    didKeys: BytesLike[],
    manifestCids: string[],
    writer: AddressLike
  ];
  export type OutputTuple = [
    didKeys: string[],
    manifestCids: string[],
    writer: string
  ];
  export interface OutputObject {
    didKeys: string[];
    manifestCids: string[];
    writer: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferStartedEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export namespace OwnershipTransferredEvent {
  export type InputTuple = [previousOwner: AddressLike, newOwner: AddressLike];
  export type OutputTuple = [previousOwner: string, newOwner: string];
  export interface OutputObject {
    previousOwner: string;
    newOwner: string;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface DidManifestRegistry extends BaseContract {
  connect(runner?: ContractRunner | null): DidManifestRegistry;
  waitForDeployment(): Promise<this>;

  interface: DidManifestRegistryInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  acceptOwnership: TypedContractMethod<[], [void], "nonpayable">;

  deleteManifestCid: TypedContractMethod<
    [didKey: BytesLike],
    [void],
    "nonpayable"
  >;

  deleteManifestCidsBatch: TypedContractMethod<
    [didKeys: BytesLike[]],
    [void],
    "nonpayable"
  >;

  getManifestCid: TypedContractMethod<[didKey: BytesLike], [string], "view">;

  owner: TypedContractMethod<[], [string], "view">;

  pendingOwner: TypedContractMethod<[], [string], "view">;

  renounceOwnership: TypedContractMethod<[], [void], "nonpayable">;

  setManifestCid: TypedContractMethod<
    [didKey: BytesLike, manifestCid: string],
    [void],
    "nonpayable"
  >;

  setManifestCidsBatch: TypedContractMethod<
    [didKeys: BytesLike[], manifestCids: string[]],
    [void],
    "nonpayable"
  >;

  transferOwnership: TypedContractMethod<
    [newOwner: AddressLike],
    [void],
    "nonpayable"
  >;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "acceptOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteManifestCid"
  ): TypedContractMethod<[didKey: BytesLike], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "deleteManifestCidsBatch"
  ): TypedContractMethod<[didKeys: BytesLike[]], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "getManifestCid"
  ): TypedContractMethod<[didKey: BytesLike], [string], "view">;
  getFunction(
    nameOrSignature: "owner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "pendingOwner"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "renounceOwnership"
  ): TypedContractMethod<[], [void], "nonpayable">;
  getFunction(
    nameOrSignature: "setManifestCid"
  ): TypedContractMethod<
    [didKey: BytesLike, manifestCid: string],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "setManifestCidsBatch"
  ): TypedContractMethod<
    [didKeys: BytesLike[], manifestCids: string[]],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "transferOwnership"
  ): TypedContractMethod<[newOwner: AddressLike], [void], "nonpayable">;

  getEvent(
    key: "ManifestCidDeleted"
  ): TypedContractEvent<
    ManifestCidDeletedEvent.InputTuple,
    ManifestCidDeletedEvent.OutputTuple,
    ManifestCidDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ManifestCidSet"
  ): TypedContractEvent<
    ManifestCidSetEvent.InputTuple,
    ManifestCidSetEvent.OutputTuple,
    ManifestCidSetEvent.OutputObject
  >;
  getEvent(
    key: "ManifestCidsBatchDeleted"
  ): TypedContractEvent<
    ManifestCidsBatchDeletedEvent.InputTuple,
    ManifestCidsBatchDeletedEvent.OutputTuple,
    ManifestCidsBatchDeletedEvent.OutputObject
  >;
  getEvent(
    key: "ManifestCidsBatchSet"
  ): TypedContractEvent<
    ManifestCidsBatchSetEvent.InputTuple,
    ManifestCidsBatchSetEvent.OutputTuple,
    ManifestCidsBatchSetEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferStarted"
  ): TypedContractEvent<
    OwnershipTransferStartedEvent.InputTuple,
    OwnershipTransferStartedEvent.OutputTuple,
    OwnershipTransferStartedEvent.OutputObject
  >;
  getEvent(
    key: "OwnershipTransferred"
  ): TypedContractEvent<
    OwnershipTransferredEvent.InputTuple,
    OwnershipTransferredEvent.OutputTuple,
    OwnershipTransferredEvent.OutputObject
  >;

  filters: {
    "ManifestCidDeleted(bytes32,address)": TypedContractEvent<
      ManifestCidDeletedEvent.InputTuple,
      ManifestCidDeletedEvent.OutputTuple,
      ManifestCidDeletedEvent.OutputObject
    >;
    ManifestCidDeleted: TypedContractEvent<
      ManifestCidDeletedEvent.InputTuple,
      ManifestCidDeletedEvent.OutputTuple,
      ManifestCidDeletedEvent.OutputObject
    >;

    "ManifestCidSet(bytes32,string,address)": TypedContractEvent<
      ManifestCidSetEvent.InputTuple,
      ManifestCidSetEvent.OutputTuple,
      ManifestCidSetEvent.OutputObject
    >;
    ManifestCidSet: TypedContractEvent<
      ManifestCidSetEvent.InputTuple,
      ManifestCidSetEvent.OutputTuple,
      ManifestCidSetEvent.OutputObject
    >;

    "ManifestCidsBatchDeleted(bytes32[],address)": TypedContractEvent<
      ManifestCidsBatchDeletedEvent.InputTuple,
      ManifestCidsBatchDeletedEvent.OutputTuple,
      ManifestCidsBatchDeletedEvent.OutputObject
    >;
    ManifestCidsBatchDeleted: TypedContractEvent<
      ManifestCidsBatchDeletedEvent.InputTuple,
      ManifestCidsBatchDeletedEvent.OutputTuple,
      ManifestCidsBatchDeletedEvent.OutputObject
    >;

    "ManifestCidsBatchSet(bytes32[],string[],address)": TypedContractEvent<
      ManifestCidsBatchSetEvent.InputTuple,
      ManifestCidsBatchSetEvent.OutputTuple,
      ManifestCidsBatchSetEvent.OutputObject
    >;
    ManifestCidsBatchSet: TypedContractEvent<
      ManifestCidsBatchSetEvent.InputTuple,
      ManifestCidsBatchSetEvent.OutputTuple,
      ManifestCidsBatchSetEvent.OutputObject
    >;

    "OwnershipTransferStarted(address,address)": TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;
    OwnershipTransferStarted: TypedContractEvent<
      OwnershipTransferStartedEvent.InputTuple,
      OwnershipTransferStartedEvent.OutputTuple,
      OwnershipTransferStartedEvent.OutputObject
    >;

    "OwnershipTransferred(address,address)": TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
    OwnershipTransferred: TypedContractEvent<
      OwnershipTransferredEvent.InputTuple,
      OwnershipTransferredEvent.OutputTuple,
      OwnershipTransferredEvent.OutputObject
    >;
  };
}
