export enum RequestError {
  IDENTIFIABLE_DATA_MISSING = 'IDENTIFIABLE_DATA_MISSING',
  EXPIRATION_DATE_REQUIRED = 'EXPIRATION_DATE_REQUIRED',
  IDENTIFIABLE_DATA_FIELD_MISSING = 'IDENTIFIABLE_DATA_FIELD_MISSING',
  ACTION_INVALID = 'ACTION_INVALID',
  REQUEST_ALREADY_PROCESSED = 'REQUEST_ALREADY_PROCESSED',
  REQUEST_NOT_FOUND = 'REQUEST_NOT_FOUND',
  UNEXPECTED_ERROR = 'UNEXPECTED_ERROR',
  STATUS_INVALID = 'STATUS_INVALID',
}
