name: Build and Deploy

on:
  push:
    branches: [dev]

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    name: Deploy Infra
    runs-on: ubuntu-latest
    environment: dev

    steps:
    - uses: actions/checkout@v2

    - name: Log into Azure
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
              
    - name: Build and push Docker image
      run: |
        az acr login --name identitycace
        docker build . -t identitycace.azurecr.io/backend:${{ github.sha }}
        docker push identitycace.azurecr.io/backend:${{ github.sha }}

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Copy files via ssh
      uses: appleboy/scp-action@master
      with:
        host: ${{ secrets.DEV_VM_HOST }}
        username: "azureuser"
        key: ${{ secrets.DEV_VM_SSH }}
        source: "."
        target: "/cace-identity"

    - name: Execute commands on the server
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.DEV_VM_HOST }}
        username: "azureuser"
        key: ${{ secrets.DEV_VM_SSH }}
        script: |
          cd /cace-identity
          npm install
          npm run start