name: Deploy to EC2

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.4
        with:
          ssh-private-key: ${{ secrets.EC2_SSH_KEY }}

      - name: Deploy to EC2 via SSH
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_HOST }} << "EOF"
            cd ~/identity

            cat > .env <<EOT
NODE_ENV=production
PORT=3000

DB_HOST=database
DB_PORT=3306
DB_USERNAME=user
DB_PASSWORD=password
DB_NAME=iovf-identity

PINATA_JWT_TOKEN=${{ secrets.PINATA_JWT_TOKEN }}
PINATA_GATEWAY=https://gateway.pinata.cloud

MAIL_ADDRESS=ida@iovf.com
MAIL_PASSWORD=${{ secrets.MAIL_PASSWORD }}

GATEWAY_URI=http://ssi-service:3000

ISSUER_PORTABLE_DID_CID=${{ secrets.ISSUER_PORTABLE_DID_CID }}

SECRET_PWD=${{ secrets.SECRET_PWD }}
SALT_ISSUER_DID=${{ secrets.SALT_ISSUER_DID }}
SALT_ISSUER_CREDENTIALS=${{ secrets.SALT_ISSUER_CREDENTIALS }}
EOT

            git checkout dev
            git pull origin dev
            docker compose down
            docker compose build
            docker compose up -d

            docker compose ps
            docker compose logs --tail=30 api
          EOF
